#requires -Version 7.0
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$PublishDirectory,
    [Parameter(Mandatory)][string]$OutputDirectory
)
$ErrorActionPreference = 'Stop'
$root = [IO.Path]::GetFullPath("$PSScriptRoot\..")
$assets = Get-Content -LiteralPath "$root\obj\project.assets.json" -Raw | ConvertFrom-Json -AsHashtable
$deps = Get-Content -LiteralPath "$PublishDirectory\PrivateTimeTrace.deps.json" -Raw | ConvertFrom-Json -AsHashtable
$cacheRoots = @($assets.packageFolders.Keys)
$packages = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
foreach ($key in $assets.libraries.Keys) {
    if ($assets.libraries[$key].type -eq 'package') { [void]$packages.Add($key) }
}
foreach ($key in $deps.libraries.Keys) {
    if ($key.StartsWith('runtimepack.')) { [void]$packages.Add($key.Substring('runtimepack.'.Length)) }
}
New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
$upstream = "$root\licenses\upstream"
Copy-Item -LiteralPath $upstream -Destination $OutputDirectory -Recurse
$inventory = foreach ($key in ($packages | Sort-Object)) {
    $id, $version = $key.Split('/', 2)
    $relativePackage = "$($id.ToLowerInvariant())\$version"
    $source = $cacheRoots | ForEach-Object { Join-Path $_ $relativePackage } | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
    if (!$source) { throw "Missing package for license audit: $key" }
    [xml]$xml = Get-Content -LiteralPath "$source\$($id.ToLowerInvariant()).nuspec" -Raw
    $metadata = $xml.SelectSingleNode('/*[local-name()="package"]/*[local-name()="metadata"]')
    $license = $metadata.SelectSingleNode('*[local-name()="license"]')
    $copyright = $metadata.SelectSingleNode('*[local-name()="copyright"]')
    $licenseUrl = $metadata.SelectSingleNode('*[local-name()="licenseUrl"]')
    $destination = Join-Path $OutputDirectory "packages\$id\$version"
    New-Item -ItemType Directory -Path $destination -Force | Out-Null
    # Preserve complete original files, including nested notices; never rewrite them.
    $licenseFiles = @(Get-ChildItem -LiteralPath $source -Recurse -File | Where-Object { $_.Name -match '^(licen[cs]e|copying|notice|third.?party.?notices?)([._-]|$)' -and $_.Extension -notin @('.dll','.xml','.json') })
    foreach ($file in $licenseFiles) {
        $relative = [IO.Path]::GetRelativePath($source, $file.FullName)
        $target = Join-Path $destination $relative
        New-Item -ItemType Directory -Path (Split-Path -Parent $target) -Force | Out-Null
        Copy-Item -LiteralPath $file.FullName -Destination $target
    }
    if (!$licenseFiles.Count) {
        $fallback = switch -Wildcard ($id) {
            'Microsoft.Data.Sqlite*' { 'EFCore-MIT.txt'; break }
            'SQLitePCLRaw.*' { 'SQLitePCLRaw-Apache-2.0.txt'; break }
            'Microsoft.Windows.SDK.BuildTools.WinApp' { 'WinAppCli-MIT.txt'; break }
            'Microsoft.Windows.SDK.*' { 'windows-sdk-license.rtf'; break }
            default { throw "No license file or reviewed override for $key" }
        }
        Copy-Item -LiteralPath "$upstream\$fallback" -Destination "$destination\$fallback"
    }
    Copy-Item -LiteralPath "$source\$($id.ToLowerInvariant()).nuspec" -Destination "$destination\package.nuspec"
    $files = @(Get-ChildItem -LiteralPath $destination -Recurse -File | Sort-Object FullName | ForEach-Object {
        [ordered]@{ path = [IO.Path]::GetRelativePath($OutputDirectory, $_.FullName).Replace('\','/'); sha256 = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant() }
    })
    [ordered]@{
        id = $id; version = $version
        scope = $(if ($id -like 'Microsoft.Windows.SDK.BuildTools*') { 'build-time' } else { 'runtime-or-transitive' })
        declaredLicense = $(if ($license) { $license.InnerText } else { 'See original vendor terms' })
        licenseUrl = $(if ($licenseUrl) { $licenseUrl.InnerText } else { "https://www.nuget.org/packages/$id/$version" })
        copyright = $(if ($copyright) { $copyright.InnerText } else { 'See original license and notices' })
        files = $files
    }
}
[ordered]@{
    formatVersion = 1
    source = 'Resolved project.assets.json and published runtime packs; build tools identified separately.'
    packages = @($inventory)
} | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath "$OutputDirectory\dependencies.json" -Encoding utf8
$table = @('# Resolved dependency license inventory', '', 'Generated by `tools/collect-licenses.ps1`. Original terms and copyright notices prevail.', '', '| Package | Version | Scope | Declared license / original terms |', '| --- | --- | --- | --- |')
foreach ($item in $inventory) {
    $table += "| $($item.id) | $($item.version) | $($item.scope) | [$($item.declaredLicense)](packages/$($item.id)/$($item.version)/) |"
}
$table += @('', 'The Windows distribution of .NET also includes [Microsoft .NET Library terms](upstream/dotnet-windows-LICENSE.txt).', '', 'NSIS installer terms: [COPYING](upstream/NSIS-COPYING.txt). SQLitePCLRaw copyright: Copyright 2014-2024 SourceGear, LLC. SQLite itself is public domain.', '', 'WebView2 Core Projection is covered by the Microsoft.Web.WebView2 package terms. Some transitive components may be present even though the app does not call their APIs.')
$table | Set-Content -LiteralPath "$OutputDirectory\README.md" -Encoding utf8
Write-Host "Collected original terms for $($inventory.Count) resolved packages, .NET Windows binaries, and NSIS."
